/* eslint-disable jsx-a11y/accessible-emoji */
import React, { FC } from 'react';

var Welcome: FC = () => {
    return (
      <section id="nice" data-tool="mdnice编辑器" data-website="https://www.mdnice.com" style={{fontSize: '16px', color: 'black', padding: '0 10px', lineHeight: '1.6', wordSpacing: '0px', letterSpacing: '0px', wordWrap: 'break-word', textAlign: 'left', marginTop: '-10px', fontFamily: '"PingFang SC", "Microsoft YaHei", sans-serif', wordBreak: 'break-all'}}>
        <p data-tool="mdnice编辑器" style={{fontSize: '16px', paddingTop: '8px', paddingBottom: '8px', margin: 0, lineHeight: '26px', color: '#666'}}><code style={{fontSize: '14px', wordWrap: 'break-word', padding: '2px 4px', borderRadius: '4px', margin: '0 2px', backgroundColor: 'rgba(27,31,35,.05)', fontFamily: 'Operator Mono, Consolas, Monaco, Menlo, monospace', wordBreak: 'break-all', color: 'hsl(216, 100%, 68%)'}}>ts-com-ui</code> 是使用 ts + react 开发一组 UI 组件库，主要用于在自己的学习中进行实践的产品。</p>
        <h2 data-tool="mdnice编辑器" style={{marginTop: '30px', marginBottom: '15px', padding: '0px', fontWeight: 'normal', color: '#333', fontSize: '1.4em', borderBottom: '1px solid hsl(216, 100%, 68%)'}}><span className="prefix" style={{display: 'none'}} /><span className="content" style={{borderBottom: '1px solid hsl(216, 100%, 68%)'}}>✨ 特性</span><span className="suffix" /></h2>
        <ul data-tool="mdnice编辑器" style={{marginTop: '8px', marginBottom: '8px', color: 'black', listStyleType: 'disc', paddingLeft: '2em'}}>
          <li style={{color: '#666'}}><section style={{marginTop: '5px', marginBottom: '5px', lineHeight: '26px', textAlign: 'left', color: 'rgb(1,1,1)', fontWeight: 500}}>🌈 提炼自 <code style={{fontSize: '14px', wordWrap: 'break-word', padding: '2px 4px', borderRadius: '4px', margin: '0 2px', backgroundColor: 'rgba(27,31,35,.05)', fontFamily: 'Operator Mono, Consolas, Monaco, Menlo, monospace', wordBreak: 'break-all', color: 'hsl(216, 100%, 68%)'}}>antd</code> 中产品的交互语言和视觉风格。</section></li><li style={{color: '#666'}}><section style={{marginTop: '5px', marginBottom: '5px', lineHeight: '26px', textAlign: 'left', color: 'rgb(1,1,1)', fontWeight: 500}}>📦 开箱即用的 React 组件。</section></li><li style={{color: '#666'}}><section style={{marginTop: '5px', marginBottom: '5px', lineHeight: '26px', textAlign: 'left', color: 'rgb(1,1,1)', fontWeight: 500}}>🛡 使用 TypeScript 开发，提供完整的类型定义文件。</section></li><li style={{color: '#666'}}><section style={{marginTop: '5px', marginBottom: '5px', lineHeight: '26px', textAlign: 'left', color: 'rgb(1,1,1)', fontWeight: 500}}>🎨 深入每个细节的主题定制能力。</section></li></ul>
        <h2 data-tool="mdnice编辑器" style={{marginTop: '30px', marginBottom: '15px', padding: '0px', fontWeight: 'normal', color: '#333', fontSize: '1.4em', borderBottom: '1px solid hsl(216, 100%, 68%)'}}><span className="prefix" style={{display: 'none'}} /><span className="content" style={{borderBottom: '1px solid hsl(216, 100%, 68%)'}}>兼容环境</span><span className="suffix" /></h2>
        <ul data-tool="mdnice编辑器" style={{marginTop: '8px', marginBottom: '8px', color: 'black', listStyleType: 'disc', paddingLeft: '2em'}}>
          <li style={{color: '#666'}}><section style={{marginTop: '5px', marginBottom: '5px', lineHeight: '26px', textAlign: 'left', color: 'rgb(1,1,1)', fontWeight: 500}}>支持 ES5 的主流浏览器</section></li></ul>
        <h2 data-tool="mdnice编辑器" style={{marginTop: '30px', marginBottom: '15px', padding: '0px', fontWeight: 'normal', color: '#333', fontSize: '1.4em', borderBottom: '1px solid hsl(216, 100%, 68%)'}}><span className="prefix" style={{display: 'none'}} /><span className="content" style={{borderBottom: '1px solid hsl(216, 100%, 68%)'}}>包地址</span><span className="suffix" /></h2>
        <p data-tool="mdnice编辑器" style={{fontSize: '16px', paddingTop: '8px', paddingBottom: '8px', margin: 0, lineHeight: '26px', color: '#666'}}><a href="https://www.npmjs.com/package/ts-com-ui" style={{textDecoration: 'none', wordWrap: 'break-word', borderBottom: '1px solid #1e6bb8', color: 'hsl(187, 100%, 45%)', fontWeight: 'normal', borderBottomColor: 'hsl(187, 100%, 45%)'}}>ts-com-ui</a></p>
        <h2 data-tool="mdnice编辑器" style={{marginTop: '30px', marginBottom: '15px', padding: '0px', fontWeight: 'normal', color: '#333', fontSize: '1.4em', borderBottom: '1px solid hsl(216, 100%, 68%)'}}><span className="prefix" style={{display: 'none'}} /><span className="content" style={{borderBottom: '1px solid hsl(216, 100%, 68%)'}}>安装</span><span className="suffix" /></h2>
        <h3 data-tool="mdnice编辑器" style={{marginTop: '30px', marginBottom: '15px', padding: '0px', fontWeight: 'normal', color: '#333', fontSize: '1.2em'}}><span className="prefix" style={{display: 'none'}} /><span className="content">使用 npm 或 yarn 安装</span><span className="suffix" style={{display: 'none'}} /></h3>
        <p data-tool="mdnice编辑器" style={{fontSize: '16px', paddingTop: '8px', paddingBottom: '8px', margin: 0, lineHeight: '26px', color: '#666'}}>我们推荐使用 npm 或 yarn 的方式进行开发，不仅可在开发环境轻松调试，也可放心地在生产环境打包部署使用，享受整个生态圈和工具链带来的诸多好处。</p>
        <pre className="custom" data-tool="mdnice编辑器" style={{marginTop: '10px', marginBottom: '10px'}}><code className="hljs" style={{overflowX: 'auto', padding: '16px', color: '#333', background: '#f8f8f8', display: '-webkit-box', fontFamily: 'Operator Mono, Consolas, Monaco, Menlo, monospace', borderRadius: '0px', fontSize: '12px', WebkitOverflowScrolling: 'touch'}}>$ npm install ts-com-ui --save{"\n"}</code></pre>
        <pre className="custom" data-tool="mdnice编辑器" style={{marginTop: '10px', marginBottom: '10px'}}><code className="hljs" style={{overflowX: 'auto', padding: '16px', color: '#333', background: '#f8f8f8', display: '-webkit-box', fontFamily: 'Operator Mono, Consolas, Monaco, Menlo, monospace', borderRadius: '0px', fontSize: '12px', WebkitOverflowScrolling: 'touch'}}>$ yarn add ts-com-ui{"\n"}</code></pre>
        <h2 data-tool="mdnice编辑器" style={{marginTop: '30px', marginBottom: '15px', padding: '0px', fontWeight: 'normal', color: '#333', fontSize: '1.4em', borderBottom: '1px solid hsl(216, 100%, 68%)'}}><span className="prefix" style={{display: 'none'}} /><span className="content" style={{borderBottom: '1px solid hsl(216, 100%, 68%)'}}>示例</span><span className="suffix" /></h2>
        <pre className="custom" data-tool="mdnice编辑器" style={{marginTop: '10px', marginBottom: '10px'}}><code className="hljs" style={{overflowX: 'auto', padding: '16px', color: '#333', background: '#f8f8f8', display: 'block', fontFamily: 'Operator Mono, Consolas, Monaco, Menlo, monospace', borderRadius: '0px', fontSize: '12px', WebkitOverflowScrolling: 'touch'}}><span className="hljs-keyword" style={{color: '#333', fontWeight: 'bold', lineHeight: '26px'}}>import</span> {"{"} Button {"}"} <span className="hljs-keyword" style={{color: '#333', fontWeight: 'bold', lineHeight: '26px'}}>from</span> <span className="hljs-string" style={{color: '#d14', lineHeight: '26px'}}>'ts-com-ui'</span>;{"\n"}<span>{"\n"}<span>ReactDOM.render(<span className="xml" style={{lineHeight: '26px'}}><span className="hljs-tag" style={{color: '#000080', fontWeight: 'normal', lineHeight: '26px'}}>&lt;<span className="hljs-name" style={{color: '#000080', fontWeight: 'normal', lineHeight: '26px'}}>Button</span> /&gt;</span>, mountNode);{"\n"}<span /></span></span></span></code></pre>
        <p data-tool="mdnice编辑器" style={{fontSize: '16px', paddingTop: '8px', paddingBottom: '8px', margin: 0, lineHeight: '26px', color: '#666'}}>引入样式</p>
        <pre className="custom" data-tool="mdnice编辑器" style={{marginTop: '10px', marginBottom: '10px'}}><code className="hljs" style={{overflowX: 'auto', padding: '16px', color: '#333', background: '#f8f8f8', display: 'block', fontFamily: 'Operator Mono, Consolas, Monaco, Menlo, monospace', borderRadius: '0px', fontSize: '12px', WebkitOverflowScrolling: 'touch'}}><span className="hljs-keyword" style={{color: '#333', fontWeight: 'bold', lineHeight: '26px'}}>import</span> <span className="hljs-string" style={{color: '#d14', lineHeight: '26px'}}>'ts-com-ui/dist/index.css'</span>;{"\n"}<span /></code></pre>
        <h3 data-tool="mdnice编辑器" style={{marginTop: '30px', marginBottom: '15px', padding: '0px', fontWeight: 'normal', color: '#333', fontSize: '1.2em'}}><span className="prefix" style={{display: 'none'}} /><span className="content">按需加载</span><span className="suffix" style={{display: 'none'}} /></h3>
        <p data-tool="mdnice编辑器" style={{fontSize: '16px', paddingTop: '8px', paddingBottom: '8px', margin: 0, lineHeight: '26px', color: '#666'}}><code style={{fontSize: '14px', wordWrap: 'break-word', padding: '2px 4px', borderRadius: '4px', margin: '0 2px', backgroundColor: 'rgba(27,31,35,.05)', fontFamily: 'Operator Mono, Consolas, Monaco, Menlo, monospace', wordBreak: 'break-all', color: 'hsl(216, 100%, 68%)'}}>ts-com-ui</code> 的 JS 代码默认支持 ES modules 的 tree shaking</p>
        <h3 data-tool="mdnice编辑器" style={{marginTop: '30px', marginBottom: '15px', padding: '0px', fontWeight: 'normal', color: '#333', fontSize: '1.2em'}}><span className="prefix" style={{display: 'none'}} /><span className="content">TypeScript</span><span className="suffix" style={{display: 'none'}} /></h3>
        <p data-tool="mdnice编辑器" style={{fontSize: '16px', paddingTop: '8px', paddingBottom: '8px', margin: 0, lineHeight: '26px', color: '#666'}}><code style={{fontSize: '14px', wordWrap: 'break-word', padding: '2px 4px', borderRadius: '4px', margin: '0 2px', backgroundColor: 'rgba(27,31,35,.05)', fontFamily: 'Operator Mono, Consolas, Monaco, Menlo, monospace', wordBreak: 'break-all', color: 'hsl(216, 100%, 68%)'}}>ts-com-ui</code> 使用 TypeScript 进行书写并提供了完整的定义文件。（不要引用 <code style={{fontSize: '14px', wordWrap: 'break-word', padding: '2px 4px', borderRadius: '4px', margin: '0 2px', backgroundColor: 'rgba(27,31,35,.05)', fontFamily: 'Operator Mono, Consolas, Monaco, Menlo, monospace', wordBreak: 'break-all', color: 'hsl(216, 100%, 68%)'}}>@types/ts-com-ui</code>）。</p>
        </section>
    );
};

export default Welcome;